/*
 * Copyright 2026 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package kpt.core.store.banking

import kpt.core.base.store.infra.StoreRegistry

/**
 * GENERATED by `./gradlew syncForkConfig` from this store's row in
 * `app-profile/app.yaml#core_store.stores`. DO NOT HAND-EDIT.
 *
 * Everything that ADDRESSES the `billRemindersMutable` store: its Koin
 * qualifier.
 *
 * Lives in the store's own package so it shares the store's lifecycle — strip the store and
 * this goes with it, with no second declaration to keep in sync.
 */
object BillRemindersMutableKeys : StoreRegistry() {
    /** Koin qualifier — `single(BillRemindersMutableKeys.Qualifier) { … }`. */
    val Qualifier = store("billRemindersMutable")
}
