/*
 * Copyright 2026 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package kpt.core.database.di

import kpt.core.database.AppDatabase
import org.koin.core.module.Module
import org.koin.dsl.module

/**
 * GENERATED by `./gradlew syncForkConfig` from `app-profile/app.yaml#database.daos`
 * — one Koin binding per declared DAO. DO NOT HAND-EDIT.
 *
 * To add a DAO: declare it in app-profile (which also puts the accessor on AppDatabase)
 * and re-run syncForkConfig. There is no wiring step — that is the point.
 *
 * Pulled in by `DatabaseModule` via `includes(GeneratedDaoBindings)`.
 */
val GeneratedDaoBindings: Module = module {
    single { get<AppDatabase>().exchangeRatesDao }
    single { get<AppDatabase>().cloudTodoDao }
    single { get<AppDatabase>().coinMarketDao }
    single { get<AppDatabase>().coinDetailDao }
    single { get<AppDatabase>().rateHistoryDao }
    single { get<AppDatabase>().watchlistDao }
    single { get<AppDatabase>().loanDao }
    single { get<AppDatabase>().billReminderDao }
    single { get<AppDatabase>().alertDao }
    single { get<AppDatabase>().interestRateSeriesDao }
}
