/*
 * Copyright 2026 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package kpt.core.store.di

import kpt.core.base.store.infra.StoreCacheManager
import kpt.core.base.store.infra.impl.StoreCacheManagerImpl
import kpt.core.store.alerts.AlertsKeys
import kpt.core.store.alerts.AlertsMutableKeys
import kpt.core.store.alerts.impl.provideAlertsStore
import kpt.core.store.alerts.impl.provideAlertsWriteStore
import kpt.core.store.banking.BillRemindersKeys
import kpt.core.store.banking.BillRemindersMutableKeys
import kpt.core.store.banking.LoansKeys
import kpt.core.store.banking.LoansMutableKeys
import kpt.core.store.banking.impl.provideBillRemindersStore
import kpt.core.store.banking.impl.provideBillRemindersWriteStore
import kpt.core.store.banking.impl.provideLoansStore
import kpt.core.store.banking.impl.provideLoansWriteStore
import kpt.core.store.calc.AmortizationCalcKeys
import kpt.core.store.calc.impl.provideAmortizationCalcStore
import kpt.core.store.cloudtodo.CloudTodoKeys
import kpt.core.store.cloudtodo.CloudTodoMutableKeys
import kpt.core.store.cloudtodo.impl.provideCloudTodoReadStore
import kpt.core.store.cloudtodo.impl.provideCloudTodoStore
import kpt.core.store.crypto.CoinDetailKeys
import kpt.core.store.crypto.CoinMarketsKeys
import kpt.core.store.crypto.impl.provideCoinDetailStore
import kpt.core.store.crypto.impl.provideCoinMarketsStore
import kpt.core.store.currency.ExchangeRatesKeys
import kpt.core.store.currency.RateHistoryKeys
import kpt.core.store.currency.impl.provideExchangeRatesStore
import kpt.core.store.currency.impl.provideRateHistoryStore
import kpt.core.store.economic.InterestRateSeriesKeys
import kpt.core.store.economic.MacroIndicatorKeys
import kpt.core.store.economic.impl.provideInterestRateSeriesStore
import kpt.core.store.economic.impl.provideMacroIndicatorStore
import kpt.core.store.emi.EmiKeys
import kpt.core.store.emi.impl.provideEmiStore
import kpt.core.store.exchange.SpotRateKeys
import kpt.core.store.exchange.impl.provideSpotRateLookupStore
import kpt.core.store.prefs.UserDataKeys
import kpt.core.store.prefs.impl.provideUserDataStore
import kpt.core.store.profile.ProfileKeys
import kpt.core.store.profile.impl.provideProfileStore
import kpt.core.store.watchlist.WatchlistKeys
import kpt.core.store.watchlist.WatchlistMutableKeys
import kpt.core.store.watchlist.impl.provideWatchlistStore
import kpt.core.store.watchlist.impl.provideWatchlistWriteStore
import org.koin.core.module.Module
import org.koin.dsl.module

/**
 * GENERATED by `./gradlew syncForkConfig` from `app-profile/app.yaml#core_store.stores`.
 * DO NOT HAND-EDIT — declare the store in app-profile and re-run syncForkConfig.
 *
 * Carries BOTH the binding and the logout registration, because they were two hand-kept
 * lists that had to agree: a store bound but never registered survives sign-out and shows
 * the previous user's cached rows to the next one on a shared device. Generating both from
 * one `logout:` field makes that drift impossible rather than merely detected by LP-1.
 *
 * `*Mutable` stores declare `logout: false`: Store5 5.1's MutableStore is not a `Store`
 * subtype so `register` cannot accept one. Their rows still go — each shares a Room table
 * with its read store, whose deleteAll wipes it.
 *
 * Pulled in by `StoreModule` via `includes(GeneratedStoreBindings)`.
 */
val GeneratedStoreBindings: Module = module {
    single(ExchangeRatesKeys.Qualifier) { provideExchangeRatesStore(api = get(), networkMonitor = get(), dao = get()) }
    single(RateHistoryKeys.Qualifier) { provideRateHistoryStore(api = get(), networkMonitor = get(), dao = get()) }
    single(CoinMarketsKeys.Qualifier) { provideCoinMarketsStore(api = get(), networkMonitor = get(), dao = get()) }
    single(CoinDetailKeys.Qualifier) { provideCoinDetailStore(api = get(), networkMonitor = get(), dao = get()) }
    single(CloudTodoKeys.Qualifier) { provideCloudTodoReadStore(api = get(), dao = get()) }
    single(CloudTodoMutableKeys.Qualifier) { provideCloudTodoStore(api = get(), dao = get(), bookkeeper = get()) }
    single(InterestRateSeriesKeys.Qualifier) { provideInterestRateSeriesStore(api = get(), config = get(), networkMonitor = get(), dao = get()) }
    single(MacroIndicatorKeys.Qualifier) { provideMacroIndicatorStore(api = get(), networkMonitor = get()) }
    single(SpotRateKeys.Qualifier) { provideSpotRateLookupStore(api = get(), networkMonitor = get(), dao = get()) }
    single(AlertsKeys.Qualifier) { provideAlertsStore(dao = get()) }
    single(AlertsMutableKeys.Qualifier) { provideAlertsWriteStore(dao = get()) }
    single(WatchlistKeys.Qualifier) { provideWatchlistStore(dao = get()) }
    single(WatchlistMutableKeys.Qualifier) { provideWatchlistWriteStore(dao = get()) }
    single(LoansKeys.Qualifier) { provideLoansStore(dao = get()) }
    single(LoansMutableKeys.Qualifier) { provideLoansWriteStore(dao = get()) }
    single(BillRemindersKeys.Qualifier) { provideBillRemindersStore(dao = get()) }
    single(BillRemindersMutableKeys.Qualifier) { provideBillRemindersWriteStore(dao = get()) }
    single(EmiKeys.Qualifier) { provideEmiStore(compute = get()) }
    single(ProfileKeys.Qualifier) { provideProfileStore(source = get()) }
    single(AmortizationCalcKeys.Qualifier) { provideAmortizationCalcStore(compute = get()) }
    single(UserDataKeys.Qualifier) { provideUserDataStore(source = get()) }

    // Logout purge — every `logout: true` store, registered at start so the manager
    // holds them before the first sign-out.
    single(createdAtStart = true) {
        val mgr = get<StoreCacheManager>() as StoreCacheManagerImpl
        mgr.register(get(ExchangeRatesKeys.Qualifier))
        mgr.register(get(RateHistoryKeys.Qualifier))
        mgr.register(get(CoinMarketsKeys.Qualifier))
        mgr.register(get(CoinDetailKeys.Qualifier))
        mgr.register(get(CloudTodoKeys.Qualifier))
        mgr.register(get(InterestRateSeriesKeys.Qualifier))
        mgr.register(get(MacroIndicatorKeys.Qualifier))
        mgr.register(get(SpotRateKeys.Qualifier))
        mgr.register(get(AlertsKeys.Qualifier))
        mgr.register(get(WatchlistKeys.Qualifier))
        mgr.register(get(LoansKeys.Qualifier))
        mgr.register(get(BillRemindersKeys.Qualifier))
        mgr.register(get(EmiKeys.Qualifier))
        mgr.register(get(ProfileKeys.Qualifier))
        mgr.register(get(AmortizationCalcKeys.Qualifier))
        mgr.register(get(UserDataKeys.Qualifier))
    }
}
