/*
 * Copyright 2026 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package kpt.core.store.economic

import kpt.core.base.store.infra.StoreRegistry
import kotlin.time.Duration.Companion.hours

/**
 * GENERATED by `./gradlew syncForkConfig` from this store's row in
 * `app-profile/app.yaml#core_store.stores`. DO NOT HAND-EDIT.
 *
 * Everything that ADDRESSES the `interestRateSeries` store: its Koin
 * qualifier, its freshness window, and its stream cache keys.
 *
 * Lives in the store's own package so it shares the store's lifecycle — strip the store and
 * this goes with it, with no second declaration to keep in sync.
 */
object InterestRateSeriesKeys : StoreRegistry() {
    /** Koin qualifier — `single(InterestRateSeriesKeys.Qualifier) { … }`. */
    val Qualifier = store("interestRateSeries")

    /** Freshness window, declared as `ttl:` in app-profile. */
    val TTL = 24.hours

    fun of(seriesId: String, days: Int): String = "economic:rates:$seriesId:${days}d"
}
