/*
 * Copyright 2025 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package kpt.core.database

import androidx.room3.AutoMigration
import androidx.room3.ColumnTypeConverters
import androidx.room3.ConstructedBy
import androidx.room3.Database
import androidx.room3.RoomDatabase
import androidx.room3.RoomDatabaseConstructor
import kpt.core.base.database.infra.dao.BookkeeperDao
import kpt.core.base.database.infra.dao.ConflictDao
import kpt.core.base.database.infra.dao.DraftDao
import kpt.core.base.database.infra.dao.FetchedAtDao
import kpt.core.base.database.infra.entity.BookkeeperEntity
import kpt.core.base.database.infra.entity.ConflictEntity
import kpt.core.base.database.infra.entity.DraftEntity
import kpt.core.base.database.infra.entity.FetchedAtEntity

/**
 * KSP-generated constructor bridge for [AppDatabase].
 *
 * Room 3 requires an `expect object` annotated via [@ConstructedBy][ConstructedBy] so that
 * the KSP compiler plugin can generate a platform-specific `actual object` containing the
 * `AppDatabase_Impl` instantiation logic.
 */
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}

/**
 * Root Room 3 database for the application.
 *
 * This is a **commonMain** definition that works across all Kotlin Multiplatform targets
 * (Android, Desktop/JVM, iOS/Native, JS, WasmJS). Platform-specific database creation
 * is handled by [kpt.core.base.database.AppDatabaseFactory] in each platform's
 * DI module — see [kpt.core.database.di.DatabaseModule].
 *
 * Room 3 uses the [ConstructedBy] annotation to delegate instance creation to
 * [AppDatabaseConstructor], whose `actual` implementation is generated by KSP on
 * every target.
 *
 * ## White-label contract (E1/C7) — this file FULL-COPIES
 * `owner: template`: a template sync blind-copies this file, no 3-way merge. It was the LAST
 * hand-merged file under the `core` modules, because Room needs ONE compile-time `entities = [...]`
 * literal — a fork's tables cannot live in a separate file the way every other seam works.
 *
 * They do not need to be MERGED, though, only re-derived. Everything project-specific — demo AND
 * fork — is DECLARED in `app-profile/app.yaml#database` and projected into the five
 * `gen-*:begin`/`gen-*:end` regions below by `./gradlew syncForkConfig`, which the sync runs
 * immediately after the copy. So the copy lands with empty regions and the regen refills them from
 * the fork's own SoT.
 *
 * Hand-editing a `gen-*` region is pointless — the next syncForkConfig overwrites it. Declare in
 * app-profile instead. Only the `infra` entities/DAOs (`Bookkeeper·Conflict·Draft·FetchedAt`) are
 * hardcoded here: they are framework, present in every fork, and never project-specific.
 *
 * Generated members are referenced by FULLY-QUALIFIED name, never via an import: ktlint's
 * `standard:import-ordering` forbids both blank lines and comments inside the import block, so a
 * sentinel region cannot live there. Same reason `AppSupabaseAnonKeys` spells out
 * `kpt.core.network.BuildKonfig.<KEY>` inside its own generated block.
 *
 * ## Fresh-fork baseline
 * The demo declarations in app-profile sit in a `# demo:begin`/`# demo:end` fence, so
 * `scripts/remove-demo.sh` strips them and the regions regenerate EMPTY. The schema history goes
 * with them (a fresh fork has no installed users to migrate) and the same script resets
 * [TEMPLATE_BASE_VERSION] to 1 — leaving a valid framework-only `@Database` at v1 with no
 * `autoMigrations`, which compiles and is coherent.
 *
 * ## Schema history (the template's own showcase DB; a fresh fork starts at v1)
 * | Version | Change |
 * |---------|--------|
 * | v3 → v4 | adds `framework_fetched_at` |
 * | v4 → v5 | adds `framework_submit_drafts` |
 * | v5 → v6 | adds `personal_watchlist` |
 * | v6 → v7 | adds `uniqueKey` column to drafts |
 * | v7 → v8 | adds `banking_loans` + `banking_bill_reminders` |
 * | v8 → v10 | adds `alerts` + `interest_rate_series`; drops `samples` |
 * | v10 → v12 | adds `cloud_todos`, `framework_write_conflicts` |
 * | v12 → v13 | adds `attemptCount` to `framework_submit_drafts` |
 */
@Database(
    entities = [
        // infra (framework) — always kept
        BookkeeperEntity::class,
        FetchedAtEntity::class,
        DraftEntity::class,
        ConflictEntity::class,
        // gen-entities:begin
        kpt.core.database.demo.currency.entity.ExchangeRatesEntity::class,
        kpt.core.database.demo.crypto.entity.CoinMarketEntity::class,
        kpt.core.database.demo.crypto.entity.CoinDetailEntity::class,
        kpt.core.database.demo.currency.entity.RateHistoryEntity::class,
        kpt.core.database.demo.watchlist.entity.WatchlistEntity::class,
        kpt.core.database.demo.banking.entity.LoanEntity::class,
        kpt.core.database.demo.banking.entity.BillReminderEntity::class,
        kpt.core.database.demo.alerts.AlertEntity::class,
        kpt.core.database.demo.economic.InterestRateSeriesEntity::class,
        kpt.core.database.demo.cloudtodo.CloudTodoEntity::class,
        // gen-entities:end
    ],
    version = AppDatabase.VERSION,
    exportSchema = true,
    autoMigrations = [
        // gen-migrations:begin
        AutoMigration(from = 3, to = 4),
        AutoMigration(from = 4, to = 5),
        AutoMigration(from = 5, to = 6),
        AutoMigration(from = 6, to = 7),
        AutoMigration(from = 7, to = 8),
        AutoMigration(from = 8, to = 10, spec = kpt.core.database.demo.MigrationSpec8to10::class),
        AutoMigration(from = 10, to = 11),
        AutoMigration(from = 11, to = 12),
        AutoMigration(from = 12, to = 13),
        // gen-migrations:end
    ],
)
// gen-converters:begin
@ColumnTypeConverters(
    kpt.core.database.demo.currency.converter.ChargeTypeConverters::class,
    kpt.core.database.demo.crypto.converter.FintechTypeConverters::class,
    kpt.core.database.demo.banking.converter.BankingTypeConverters::class,
)
// gen-converters:end
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {

    // infra (framework) — always kept
    abstract val bookkeeperDao: BookkeeperDao
    abstract val fetchedAtDao: FetchedAtDao
    abstract val draftDao: DraftDao
    abstract val conflictDao: ConflictDao

    // gen-daos:begin
    abstract val exchangeRatesDao: kpt.core.database.demo.currency.dao.ExchangeRatesDao
    abstract val cloudTodoDao: kpt.core.database.demo.cloudtodo.CloudTodoDao
    abstract val coinMarketDao: kpt.core.database.demo.crypto.dao.CoinMarketDao
    abstract val coinDetailDao: kpt.core.database.demo.crypto.dao.CoinDetailDao
    abstract val rateHistoryDao: kpt.core.database.demo.currency.dao.RateHistoryDao
    abstract val watchlistDao: kpt.core.database.demo.watchlist.dao.WatchlistDao
    abstract val loanDao: kpt.core.database.demo.banking.dao.LoanDao
    abstract val billReminderDao: kpt.core.database.demo.banking.dao.BillReminderDao
    abstract val alertDao: kpt.core.database.demo.alerts.AlertDao
    abstract val interestRateSeriesDao: kpt.core.database.demo.economic.InterestRateSeriesDao
    // gen-daos:end

    companion object {
        // `scripts/remove-demo.sh` resets this to 1 (fresh-fork baseline) via a targeted sed —
        // the migration history is declared in app-profile behind the demo fence and is stripped
        // with it, so the version must drop in lockstep or Room sees migrations past its version.
        /** Template-owned base schema version — the TEMPLATE bumps this on its own schema changes. */
        const val TEMPLATE_BASE_VERSION = 13

        /**
         * Effective DB schema version = template base + the fork's offset ([ForkDatabaseConfig],
         * fork-owned). A fork bumping its schema edits `VERSION_OFFSET` in its own file, never this
         * base — so fork and template version bumps never collide on the same line (conflict-free
         * adoption). Both operands are `const`, so this stays a compile-time constant Room accepts.
         */
        const val VERSION = TEMPLATE_BASE_VERSION + ForkDatabaseConfig.VERSION_OFFSET

        /** Fork-unique on-disk DB filename — single source of truth is [DatabaseConfig.NAME]
         *  (appId-derived, regenerated by `syncForkConfig`). All platform builders read this. */
        const val DATABASE_NAME = DatabaseConfig.NAME
    }
}
