/*
 * Copyright 2026 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package kpt.core.network.di

import kpt.core.base.network.restApi
import kpt.core.base.network.supabaseApi
import kpt.core.network.demo.appconfig.api.AppConfigApi
import kpt.core.network.demo.cloudtodo.api.createJsonPlaceholderApi
import kpt.core.network.demo.crypto.api.createCoinGeckoApi
import kpt.core.network.demo.currency.api.createFrankfurterApi
import kpt.core.network.demo.economic.api.createFredApi
import kpt.core.network.demo.economic.api.createWorldBankApi
import org.koin.core.module.Module
import org.koin.dsl.module

/**
 * GENERATED by `./gradlew syncForkConfig` from `app-profile/app.yaml#network.access_points`
 * — one Koin binding per access point that declares `api:`. DO NOT HAND-EDIT.
 *
 * To add an API: declare the endpoint (with its `api:` FQN) in app-profile, write the API
 * type, and re-run syncForkConfig. There is no wiring step — that is the point.
 *
 * Pulled in by `NetworkModule` via `includes(GeneratedApiBindings)`.
 */
val GeneratedApiBindings: Module = module {
    supabaseApi("supabase_data") { AppConfigApi(it) }
    restApi("jsonplaceholder") { it.createJsonPlaceholderApi() }
    restApi("frankfurter") { it.createFrankfurterApi() }
    restApi("coingecko") { it.createCoinGeckoApi() }
    restApi("fred") { it.createFredApi() }
    restApi("worldbank") { it.createWorldBankApi() }
}
